name: jumpat
version: 2.0.0+1
publish_to: none
description: Jumppasovellus.
environment:
  sdk: ">=2.19.2 <3.0.0"
dependencies:
  auto_route: ^5.0.4
  cupertino_icons: ^1.0.2
  drift: ^2.5.0
  fast_immutable_collections: ^8.2.0
  flutter:
    sdk: flutter
  flutter_expandable_fab: ^1.7.0
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  flutter_material_color_picker: ^1.1.0+2
  flutter_slidable: ^2.0.0
  fpdart: ^0.4.1
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.2.0
  meta: ^1.8.0
  numberpicker: ^2.1.1
  path: ^1.8.2
  path_provider: ^2.0.12
  riverpod_annotation: ^1.2.1
  shared_preferences: ^2.0.17
  tsid_creator:
    git:
      url: https://github.com/jerepenttinen/tsid_creator
      ref: master

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  custom_lint: ^0.2.11
  drift_dev: ^2.5.2
  flutter_test:
    sdk: flutter
  pubspec_dependency_sorter: ^1.0.3
  riverpod_generator: ^1.1.1
  riverpod_lint: ^1.0.1
  test: ^1.22.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  generate: true
