name: jumpat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.2 <3.0.0"
dependencies:
  auto_route: ^5.0.4
  cupertino_icons: ^1.0.2
  fast_immutable_collections: ^8.2.0
  flutter:
    sdk: flutter
  flutter_expandable_fab: ^1.7.0
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  flutter_material_color_picker: ^1.1.0+2
  flutter_slidable: ^2.0.0
  fpdart: ^0.4.1
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.2.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  meta: ^1.8.0
  numberpicker: ^2.1.1
  path: ^1.8.2
  path_provider: ^2.0.12
  riverpod_annotation: ^1.2.1
  rxdart: ^0.27.7
  shared_preferences: ^2.0.17
  uuid: ^3.0.7

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.5
  pubspec_dependency_sorter: ^1.0.3
  riverpod_generator: ^1.1.1
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  generate: true
